export const workflow = `# Automatic professional photo editing

Use the native engine as a nondestructive editor. Choose treatment from the photo and the user's intent, then verify the actual rendered result. Professional quality is a visual judgment, not a histogram target or the successful completion of a tool call.

1. Read rapidraw_capabilities with detail: "overview" and inspect rapidraw_models when AI work is needed. Request only needed schema_paths (for example properties.temperature) and reuse them until schema_id changes. The full rapidraw://adjustment-schema resource remains available. Open the source with rapidraw_open_photo; keep the returned session_id and revision. Source photos and sidecars stay unchanged.
2. Render an original overview and inspect the subject, composition, light, white balance, texture and distractions. Use rapidraw_analyze for exposure/clipping context. Record a short edit intention appropriate to the image. Do not blindly neutralize intentional warm light or dramatic shadows.
3. Set restrained global exposure, tone, white balance, color and crop adjustments. Use expected_revision on edits to catch stale state. Auto-adjust and presets are starting points that require review.
4. Generate or construct selective masks when they improve the subject/background relationship. Render each mask with mask_mode: "overlay" to compare the aligned photograph, overlay and grayscale selection; inspect edge spill and feathering, then apply local adjustments. Use geometric masks when an AI model is unavailable and the shape is adequate; do not claim semantic masking succeeded.
5. Render the result and native-detail regions. Check texture, noise, sharpening halos, skin/plumage neutrality, clipping, mask edges, geometry, crop intent and distracting artifacts. Save a user-valued reference with rapidraw_save_version. Use rapidraw_render_compare for temporary temperature and mask-off alternatives with matching geometry; use rapidraw_inspect_adjustments to inspect combined local exposure and actual rendered differences without changing the edit. Revisit a weak edit using history/undo. Compare the original when needed. Statistics complement visual judgment.
6. Retouch only when the user requested or clearly authorized content removal. Choose local clone/heal/inpaint where suitable. Remote generative mode requires explicit selection and sends image content to the configured service. Do not remove truthful scene content just to improve a numerical score.
7. Stop iterating when the result meets the stated intent without new defects; if the source cannot support the desired result, state the specific limitation. Save the session and reusable recipe. Export a full-resolution master and an appropriately sized delivery file inside the workspace. Inspect the exported image, dimensions, format, bit depth and metadata results.
8. For a batch, inspect each source and review each output. Share a style only where the lighting and subject justify it. Check every batch item outcome; partial success is not completion.

Coordinates: use the coordinate_space and mask schemas returned by capabilities. A crop, a preview pixel coordinate and the full source pixel coordinate are different spaces; use rapidraw_map_coordinates with the actual displayed dimensions and region. rapidraw_sample_region measures a chosen neutral region and can suggest white balance without applying it; inspect its assumption and compare the result. rapidraw_preflight reports current model, geometry and resource constraints. Original RAW working copies with their saved .rrdata can be opened in the RapidRAW GUI for manual continuation. Linear denoised TIFF working copies require the saved MCP session to retain matching RAW interpretation; reopening those TIFFs directly in the GUI can change their appearance.

For long denoising, use rapidraw_start_denoise and keep job_id. Poll rapidraw_get_job and inspect result_session_id after success; its edits were captured when the job started. rapidraw_cancel_job cooperatively stops the worker without killing the engine. After restart inspect rapidraw_list_jobs; rapidraw_resume_job restarts interrupted work from captured input, not a tile checkpoint.

For other expensive local operations, rapidraw_start_operation captures input state and uses a separate native worker. Poll rapidraw_get_operation_job; cancel/resume only through its operation-job tools. Returned edits belong to a new independent session. Use rapidraw_fork_session for alternatives and portable session bundles to move edits with their owned source and dependencies.

Keep a short per-photo checkpoint with source identity, session/revision, accepted version, mask IDs, geometry, saved-state and render paths, intent, accepted qualities and unresolved defects. After context reset, reconcile it with live state and reopen relevant visual evidence. Session asset descriptors are verifiable references: passing read-back state into a mutating call rehydrates them against the live session (stale ones error, so re-read first); preserve full state with native save/bundle operations.

Reliability: a failed tool is an error, not a blank edit. Missing models, invalid masks and unsupported formats must be resolved explicitly. After a bridge timeout or crash, reconnect and inspect saved state before retrying; mutations are never automatically replayed.\n`;
